### ISSUE TITLE
Twig-Image Filter defekt

### ISSUE THREAD

**Issue by mj1985** [heimrichhannot/contao-utils-bundle#66]
**Context**
Contao version: 4.13.23
Bundle version: 2.228.0 / 2.227.1
PHP version: 8.1

**Description**
Seit Version 2.226.1 funktioniert der Image-Filter aus diesem Bundle nicht mehr richtig. Getestet habe ich dieses mit dem Beispiel:
`{{box.image|image([0,0,6],{'href' : 'https://google.de', 'linkTitle' : 'vmd.content.more.default'|trans})|raw }}`
und unserem alten Code
`{{ img.image|image(imageSize, {'class': imageClass|trans})|raw }} `
wobei imageClass vorher wie folgt festgelegt ist:
`{% set imageClass = 'img-fluid img-parallax w-100' %}`

Ausgabe: ImageClass wird nicht berücksichtigt
![image](https://github.com/heimrichhannot/contao-utils-bundle/assets/5830093/7cff9dbb-85c0-4469-bec0-7c575037d78b)

**Comment by koertho** [comment]
@mj1985 Sorry for not responding until now. I just released an update that address another issue with the image filter, maybe it also solves your issue.

**Comment by mj1985** [comment]
Unfortunately 2.228.2 doesn't fixes the issue.
This still doesn't work:
`{{ image|image(imageSize, {class: 'img-fluid'})|raw }}`
class and img.class are still empty.
![image](https://github.com/heimrichhannot/contao-utils-bundle/assets/5830093/19460633-8d88-42c0-abc8-f13d77bbea1c)
CSS classes via image-sizes works fine.

**Comment by koertho** [comment]
@vvohh Could you have a look into this?

**Comment by vvohh** [comment]
Hello @mj1985 , most of the available options didnt make it to the final rendering of the image, this should be fixed in the latest version (as of 2.230.1)

**Comment by mj1985** [comment]
@vvohh thanks, the issue has been resolved
